<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EvalHarness.Core\EvalHarness.Core.csproj" />
    <ProjectReference Include="..\EvalHarness.RagClient\EvalHarness.RagClient.csproj" />
    <ProjectReference Include="..\EvalHarness.Evaluators\EvalHarness.Evaluators.csproj" />
    <ProjectReference Include="..\EvalHarness.Runner\EvalHarness.Runner.csproj" />
  </ItemGroup>

</Project>
